# Copyright 2025 Kiruba Sankar Swaminathan. All rights reserved.
# Use of this source code is governed by the GNU AGPL v3
# license that can be found in the LICENSE file.

version("1.0.0");
selectors("worker");
resources {
  memory { min("64 mb"); max("256 mb"); };
  cpu { min("100 mhz"); max("500 mhz"); };
  ports {
    compose_api_http_port { };
  };
};
health_check {
  timeout_seconds(5);
  wait { attempts(30); interval_seconds(1); };
  readiness {
    http {
      port("compose_api_http_port");
      path("/");
      expect_status(200);
      scheme("http");
    };
  };
};
