# Copyright 2025 Kiruba Sankar Swaminathan. All rights reserved.
# Use of this source code is governed by the GNU AGPL v3
# license that can be found in the LICENSE file.

version("1.0.0");
selectors("worker");
resources {
  memory { min("32 mb"); max("128 mb"); };
  cpu { min("50 mhz"); max("200 mhz"); };
};
health_check {
  timeout_seconds(5);
  wait { attempts(20); interval_seconds(1); };
  liveness {
    ssh { command("systemctl is-active kive-systemd_service.service"); };
  };
};
